name = "pacific-industrial-sourcing"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2026-08-26"

[env.production]
vars = { }

[env.production.secrets]
# RESEND_API_KEY will be set via Cloudflare Pages UI
